In [1]:
# Let printing work the same in Python 2 and 3
from __future__ import print_function

# NumPy
The NumPy package provides the "ndarray" object. The NumPy array is used to contain data of uniform type with an arbitrary number of dimensions. NumPy then provides basic mathematical and array methods to lay down the foundation for the entire SciPy ecosystem. The following import statement is the generally accepted convention for NumPy.

In [2]:
import numpy as np

## Array Creation
There are several ways to make NumPy arrays. An array has three particular attributes that can be queried: shape, size and the number of dimensions.

In [3]:
a = np.array([1, 2, 3])
print(a.shape)
print(a.size)
print(a.ndim)

(3,)
3
1


In [11]:
x = np.arange(100)
print(x.shape)
print(x.size)
print(x.ndim)
print(x)

(100,)
100
1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
y = np.random.rand(5, 80)
print(y.shape)
print(y.size)
print(y.ndim)
print(y)

(5, 80)
400
2
[[0.96210955 0.3542796  0.63007663 0.3832512  0.63081367 0.96346164
  0.73581426 0.38600876 0.55480421 0.25859335 0.28223128 0.04939809
  0.85773629 0.86932257 0.57844979 0.95534299 0.29157137 0.99682976
  0.25295832 0.90965867 0.7428086  0.68231188 0.26617745 0.80269964
  0.45237039 0.1708144  0.5136236  0.88669352 0.33586421 0.74592201
  0.05916458 0.25726315 0.92694601 0.16928856 0.89613274 0.3097267
  0.919695   0.19507967 0.01060956 0.35966243 0.18385011 0.81030822
  0.10975776 0.92932246 0.64994017 0.20522726 0.06535242 0.62506843
  0.05952537 0.44546975 0.49499189 0.42019258 0.16208457 0.99717486
  0.10500733 0.35847601 0.74299279 0.16729523 0.59238864 0.07709559
  0.79116669 0.91672631 0.92590197 0.24933576 0.07010493 0.0771878
  0.80645237 0.34933071 0.33325338 0.46452765 0.41879928 0.38862598
  0.12015426 0.04378667 0.84460816 0.26736949 0.20524276 0.72560387
  0.54596172 0.2052798 ]
 [0.50920177 0.38430852 0.30716536 0.1804624  0.64330227 0.35178122
  0.1782695

## Array Manipulation
How to change the shape of an array without a copy!

In [15]:
x.shape = (20, 5)
print(x)
print(x.size)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
100


NumPy can even automatically figure out the size of at most one dimension for you.

In [16]:
y.shape = (4, 20, -1)
print(y.shape)
print(y)
print(y.size)

(4, 20, 5)
[[[0.96210955 0.3542796  0.63007663 0.3832512  0.63081367]
  [0.96346164 0.73581426 0.38600876 0.55480421 0.25859335]
  [0.28223128 0.04939809 0.85773629 0.86932257 0.57844979]
  [0.95534299 0.29157137 0.99682976 0.25295832 0.90965867]
  [0.7428086  0.68231188 0.26617745 0.80269964 0.45237039]
  [0.1708144  0.5136236  0.88669352 0.33586421 0.74592201]
  [0.05916458 0.25726315 0.92694601 0.16928856 0.89613274]
  [0.3097267  0.919695   0.19507967 0.01060956 0.35966243]
  [0.18385011 0.81030822 0.10975776 0.92932246 0.64994017]
  [0.20522726 0.06535242 0.62506843 0.05952537 0.44546975]
  [0.49499189 0.42019258 0.16208457 0.99717486 0.10500733]
  [0.35847601 0.74299279 0.16729523 0.59238864 0.07709559]
  [0.79116669 0.91672631 0.92590197 0.24933576 0.07010493]
  [0.0771878  0.80645237 0.34933071 0.33325338 0.46452765]
  [0.41879928 0.38862598 0.12015426 0.04378667 0.84460816]
  [0.26736949 0.20524276 0.72560387 0.54596172 0.2052798 ]
  [0.50920177 0.38430852 0.30716536 0.1804624

## Array Indexing

In [17]:
# Scalar Indexing
print(x)
print(x[2])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]
 [70 71 72 73 74]
 [75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
[10 11 12 13 14]


In [31]:
# Slicing
print(x[2:5])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [32]:
# Advanced slicing
print("First 5 rows\n", x[:5])
print("Row 18 to the end\n", x[18:])
print("Last 5 rows\n", x[-5:])
print("Reverse the rows\n", x[::-1])

First 5 rows
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Row 18 to the end
 [[90 91 92 93 94]
 [95 96 97 98 99]]
Last 5 rows
 [[75 76 77 78 79]
 [80 81 82 83 84]
 [85 86 87 88 89]
 [90 91 92 93 94]
 [95 96 97 98 99]]
Reverse the rows
 [[95 96 97 98 99]
 [90 91 92 93 94]
 [85 86 87 88 89]
 [80 81 82 83 84]
 [75 76 77 78 79]
 [70 71 72 73 74]
 [65 66 67 68 69]
 [60 61 62 63 64]
 [55 56 57 58 59]
 [50 51 52 53 54]
 [45 46 47 48 49]
 [40 41 42 43 44]
 [35 36 37 38 39]
 [30 31 32 33 34]
 [25 26 27 28 29]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]]


In [33]:
# Boolean Indexing
print(x[(x % 2) == 0])

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


In [34]:
# Fancy Indexing -- Note the use of a list, not tuple!
print(x[[1, 3, 8, 9, 2]])

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [40 41 42 43 44]
 [45 46 47 48 49]
 [10 11 12 13 14]]


## Broadcasting
Broadcasting is a very useful feature of NumPy that will let arrays with differing shapes still be used together. In most cases, broadcasting is faster, and it is more memory efficient than the equivalent full array operation.

In [35]:
print("Shape of X:", x.shape)
print("Shape of Y:", y.shape)

Shape of X: (20, 5)
Shape of Y: (4, 20, 5)


Now, here are three identical assignments. The first one takes full advantage of broadcasting by allowing NumPy to automatically add a new dimension to the *left*. The second explicitly adds that dimension with the special NumPy alias "np.newaxis". These first two creates a singleton dimension without any new arrays being created. That singleton dimension is then implicitly tiled, much like the third example to match with the RHS of the addition operator. However, unlike the third example, the broadcasting merely re-uses the existing data in memory.

In [18]:
#broadcasting lo fa automaticamente, non vengono creati altri oggetti (aggiunge dimensione a sinistra)
a = x + y
#alternativa:
print(a.shape)
b = x[np.newaxis, :, :] + y
print(b.shape)
c = np.tile(x, (4, 1, 1)) + y
print(c.shape)
print("Are a and b identical?", np.all(a == b))
print("Are a and c identical?", np.all(a == c))
print(a)

(4, 20, 5)
(4, 20, 5)
(4, 20, 5)
Are a and b identical? True
Are a and c identical? True
[[[ 0.96210955  1.3542796   2.63007663  3.3832512   4.63081367]
  [ 5.96346164  6.73581426  7.38600876  8.55480421  9.25859335]
  [10.28223128 11.04939809 12.85773629 13.86932257 14.57844979]
  [15.95534299 16.29157137 17.99682976 18.25295832 19.90965867]
  [20.7428086  21.68231188 22.26617745 23.80269964 24.45237039]
  [25.1708144  26.5136236  27.88669352 28.33586421 29.74592201]
  [30.05916458 31.25726315 32.92694601 33.16928856 34.89613274]
  [35.3097267  36.919695   37.19507967 38.01060956 39.35966243]
  [40.18385011 41.81030822 42.10975776 43.92932246 44.64994017]
  [45.20522726 46.06535242 47.62506843 48.05952537 49.44546975]
  [50.49499189 51.42019258 52.16208457 53.99717486 54.10500733]
  [55.35847601 56.74299279 57.16729523 58.59238864 59.07709559]
  [60.79116669 61.91672631 62.92590197 63.24933576 64.07010493]
  [65.0771878  66.80645237 67.34933071 68.33325338 69.46452765]
  [70.41879928 

Another example of broadcasting two 1-D arrays to make a 2-D array.

In [25]:
x = np.arange(-5, 5, 0.1)
y = np.arange(-8, 8, 0.25)
print(x.shape, y.shape)
z = x[np.newaxis, :] * y[:, np.newaxis]
#z = x + y  broadcasting a sinistra in questo caso non funziona
print(z.shape)
#print(x)

(100,) (64,)
(64, 100)


In [44]:
# More concisely
y, x = np.ogrid[-8:8:0.25, -5:5:0.1]
print(x.shape, y.shape)
z = x * y
print(z.shape)
#print(x)

(1, 100) (64, 1)
(64, 100)
[[-5.  -4.9 -4.8 -4.7 -4.6 -4.5 -4.4 -4.3 -4.2 -4.1 -4.  -3.9 -3.8 -3.7
  -3.6 -3.5 -3.4 -3.3 -3.2 -3.1 -3.  -2.9 -2.8 -2.7 -2.6 -2.5 -2.4 -2.3
  -2.2 -2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9
  -0.8 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5
   0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9
   2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3
   3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7
   4.8  4.9]]
